#!/usr/bin/env node
/* ============================================================================
   build-seo.mjs — makes the site readable by Google.
   ----------------------------------------------------------------------------
   WHY THIS EXISTS
   The two .dc.html pages draw everything with JavaScript after loading React
   and Babel from a CDN. A search engine that fetches the page sees an empty
   shell. This script reads content.js and diary.js and writes real pages whose
   text, title, description and structured data are already in the HTML. The
   interactive site then mounts on top, so visitors see no difference.

   YOU NEVER EDIT THE FILES THIS WRITES. They are regenerated by publish.sh
   every time the site is published:

     index.html                 English home page      https://tkuhara.github.io/
     ja.html                    Japanese home page
     project-<id>.html          one page per project (English)
     project-<id>-ja.html       one page per project (Japanese)
     diary.html                 the diary
     sitemap.xml, robots.txt    the map Google reads

   Run by hand:   node build-seo.mjs
   No dependencies — plain Node 18+.
   ========================================================================== */

import { readFileSync, writeFileSync, statSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url));
const at = (...p) => join(ROOT, ...p);
const load = async f => import(pathToFileURL(at(f)).href + '?t=' + Date.now());

const C = await load('content.js');
const D = await load('diary.js');

const PORTFOLIO_SRC = 'Research Portfolio.dc.html';
const DIARY_SRC = 'Diary.dc.html';
const LANGS = ['en', 'ja'];

/* ---- settings: content.js may export SEO to override any of these -------- */
const SEO = Object.assign({
  siteUrl: 'https://tkuhara.github.io',
  title: {
    en: 'Takumi Kuhara (久原 拓巳) | Haptics & Vibrotactile Perception Research',
    ja: '久原 拓巳 (Takumi Kuhara) | 触覚・振動知覚の研究 — 名古屋工業大学'
  },
  description: {
    en: 'Takumi Kuhara is a doctoral student at Nagoya Institute of Technology researching vibrotactile perception, haptics and multisensory experience. Projects, publications, CV and contact.',
    ja: '久原拓巳（くはら たくみ）— 名古屋工業大学大学院 博士後期課程。振動触覚の知覚メカニズム、ハプティクス、多感覚体験を研究しています。研究プロジェクト、論文、CV、連絡先。'
  },
  diaryTitle: 'Diary — Takumi Kuhara (久原 拓巳)',
  diaryDescription: 'Short notes by Takumi Kuhara on haptics research, papers, gadgets and research life. 触覚研究・論文・ガジェットについての短いメモ。',
  alternateNames: ['久原 拓巳', '久原拓巳', 'Kuhara Takumi'],
  affiliation: { name: 'Nagoya Institute of Technology', ja: '名古屋工業大学', url: 'https://www.nitech.ac.jp/' }
}, C.SEO || {});

const SITE = SEO.siteUrl.replace(/\/$/, '');

/* ---- helpers ------------------------------------------------------------- */
const esc = s => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const tr = (v, lang) => v == null ? '' : typeof v === 'string' ? v : (v[lang] || v.en || v.ja || '');
// language a bilingual value actually comes out in (for lang="" attributes)
const langOf = (v, lang) => (v && typeof v === 'object' && !v[lang]) ? (v.en ? 'en' : 'ja') : lang;
const abs = u => /^(https?:|mailto:)/.test(u) ? u : SITE + '/' + u.replace(/^\.?\//, '').split('/').map(encodeURIComponent).join('/');
const ext = u => /^https?:/.test(u);
const clip = (s, n) => s.length <= n ? s : s.slice(0, n - 1).replace(/[\s,.;、。]+\S*$/, '') + '…';
const jsonld = o => '<script type="application/ld+json">' + JSON.stringify(o).replace(/</g, '\\u003c') + '</script>';
const isoDate = d => d.toISOString().slice(0, 10);
const mtime = f => existsSync(at(f)) ? statSync(at(f)).mtime : new Date(0);

const homeFile = lang => lang === 'en' ? './' : 'ja.html';
const homeUrl = lang => lang === 'en' ? SITE + '/' : SITE + '/ja.html';
const projFile = (id, lang) => `project-${id}${lang === 'en' ? '' : '-ja'}.html`;
const other = lang => lang === 'en' ? 'ja' : 'en';

function linksOf(o, ui) {
  const out = [];
  if (o.doi) out.push({ label: ui.link_doi, href: o.doi });
  if (o.arxiv) out.push({ label: 'arXiv', href: o.arxiv });
  if (o.pdf) out.push({ label: ui.link_pdf, href: o.pdf });
  if (o.video) out.push({ label: ui.link_video, href: o.video });
  if (o.page) out.push({ label: 'Page', href: o.page });
  if (o.code) out.push({ label: 'Code', href: o.code });
  (o.more || []).forEach(l => l && l.href && out.push({ label: l.label || 'Link', href: l.href }));
  return out;
}
const linkRow = links => links.length
  ? '<p class="pr-links">' + links.map(l => `<a href="${esc(l.href)}"${ext(l.href) ? ' rel="noopener"' : ''}>${esc(l.label)}</a>`).join(' ') + '</p>'
  : '';

/* ---- structured data ----------------------------------------------------- */
const sameAs = [...new Set(C.SOCIALS.filter(s => s.url).map(s => s.url).concat(C.PROFILE.researchmap || []))];
const PERSON_ID = SITE + '/#person';

function personLd(lang) {
  return {
    '@type': 'Person', '@id': PERSON_ID,
    name: tr(C.PROFILE.name, 'en'),
    alternateName: SEO.alternateNames,
    givenName: 'Takumi', familyName: 'Kuhara',
    url: SITE + '/',
    image: C.PROFILE.portrait ? abs(C.PROFILE.portrait) : undefined,
    jobTitle: tr(C.PROFILE.role, lang),
    description: tr(C.PROFILE.tagline, lang),
    affiliation: { '@type': 'CollegeOrUniversity', name: SEO.affiliation.name, alternateName: SEO.affiliation.ja, url: SEO.affiliation.url },
    alumniOf: { '@type': 'CollegeOrUniversity', name: SEO.affiliation.name, url: SEO.affiliation.url },
    knowsAbout: C.PROFILE.interests.map(i => tr(i, lang)),
    knowsLanguage: ['ja', 'en'],
    sameAs
  };
}
const articleLd = p => ({
  '@type': 'ScholarlyArticle',
  headline: tr(p.title, 'en'), name: tr(p.title, 'en'),
  inLanguage: p.title.en ? 'en' : 'ja',
  author: tr(p.authors, 'en').split(/,\s*/).map(n => /Takumi Kuhara|久原\s*拓巳/.test(n) ? { '@id': PERSON_ID } : { '@type': 'Person', name: n }),
  datePublished: String(p.year).slice(0, 4),
  isPartOf: { '@type': 'Periodical', name: tr(p.venue, 'en').replace(/,\s*\d.*$/, '') },
  sameAs: p.doi || undefined, url: p.doi || undefined
});
const websiteLd = { '@type': 'WebSite', '@id': SITE + '/#website', url: SITE + '/', name: 'Takumi Kuhara', alternateName: '久原 拓巳', inLanguage: ['en', 'ja'], author: { '@id': PERSON_ID } };

/* ---- shared <head> ------------------------------------------------------- */
const STATIC_CSS = `
x-dc{display:none!important}
:root[data-theme="dark"]{--color-bg:#141312;--color-surface:#201e1d;--color-text:#f3f2f2;--color-divider:color-mix(in srgb,#f3f2f2 40%,transparent);--color-accent:#ff563c;color-scheme:dark}
body{margin:0;background:var(--color-bg);color:var(--color-text)}
body:has(#prerender) #dc-root{display:none}
#prerender{font-family:var(--font-body);line-height:1.6}
#prerender a{color:var(--color-accent);text-underline-offset:3px}
.pr-bar{border-bottom:2px solid var(--color-divider)}
.pr-bar>div,.pr-wrap{max-width:1180px;margin:0 auto;padding-left:24px;padding-right:24px}
.pr-narrow .pr-bar>div,.pr-narrow .pr-wrap{max-width:820px}
.pr-bar>div{display:flex;flex-wrap:wrap;gap:12px 22px;align-items:center;justify-content:space-between;padding-top:14px;padding-bottom:14px}
.pr-bar .pr-brand{font-family:var(--font-heading);font-weight:800;font-size:17px;color:var(--color-text)!important;text-decoration:none}
.pr-bar nav{display:flex;flex-wrap:wrap;gap:8px 22px;font-size:13px;letter-spacing:.04em;text-transform:uppercase;font-weight:600}
.pr-bar nav a{color:var(--color-text)!important;text-decoration:none;opacity:.62}
.pr-hero{padding-top:72px;padding-bottom:56px;display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:40px;align-items:end}
.pr-hero img{aspect-ratio:3/4;max-width:280px;width:100%;height:auto;object-fit:cover;border:2px solid var(--color-divider);justify-self:end;display:block}
.pr-kicker{font-size:13px;letter-spacing:.1em;text-transform:uppercase;font-weight:600;opacity:.6;margin:0 0 16px}
#prerender h1{font-family:var(--font-heading);font-weight:800;font-size:clamp(44px,8vw,104px);line-height:.94;letter-spacing:-.03em;margin:0 0 24px}
#prerender .pr-article h1{font-size:clamp(36px,6vw,72px);line-height:1.02;letter-spacing:-.02em;max-width:16ch;margin-bottom:20px}
.pr-lead{font-size:clamp(16px,1.8vw,20px);line-height:1.5;max-width:44ch;margin:0;opacity:.78}
.pr-sec{border-top:2px solid var(--color-divider)}
.pr-sec>.pr-wrap{padding-top:56px;padding-bottom:56px}
#prerender h2{font-family:var(--font-heading);font-weight:800;font-size:clamp(28px,4vw,44px);letter-spacing:-.02em;margin:0 0 28px}
#prerender h3{font-family:var(--font-heading);font-weight:800;font-size:13px;letter-spacing:.1em;text-transform:uppercase;margin:40px 0 0;padding-bottom:10px;border-bottom:2px solid var(--color-divider)}
.pr-cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:2px;background:var(--color-divider);border:2px solid var(--color-divider);list-style:none;margin:0;padding:0}
.pr-cards li{background:var(--color-bg);padding:22px;display:flex;flex-direction:column;gap:12px}
.pr-cards img{display:block;width:100%;aspect-ratio:16/10;object-fit:contain;background:var(--color-surface);border:1px solid var(--color-divider)}
#prerender .pr-cards h3,#prerender .pr-cards h4{font-family:var(--font-heading);font-weight:800;font-size:24px;line-height:1.1;letter-spacing:-.015em;text-transform:none;margin:0;padding:0;border:0}
.pr-cards h3 a,.pr-cards h4 a{color:var(--color-text)!important;text-decoration:none}
.pr-cards p{margin:0;font-size:14px;opacity:.7}
.pr-cards .pr-k{font-size:12px;letter-spacing:.1em;text-transform:uppercase;font-weight:600;color:var(--color-accent);opacity:1}
.pr-text{font-size:17px;line-height:1.7;max-width:62ch;margin:0 0 20px}
.pr-tags{list-style:none;display:flex;flex-wrap:wrap;gap:8px;padding:0;margin:0}
.pr-tags li{border:2px solid var(--color-divider);padding:5px 12px;font-size:12px;letter-spacing:.06em;text-transform:uppercase;font-weight:600}
.pr-list{list-style:none;padding:0;margin:0}
.pr-list li{display:grid;grid-template-columns:72px 1fr;gap:20px;padding:16px 0;border-bottom:1px solid var(--color-divider)}
.pr-list.pr-wide li{grid-template-columns:180px 1fr}
.pr-list .pr-y{font-family:var(--font-heading);font-weight:800;font-size:15px;opacity:.55}
.pr-list p{margin:0;font-size:14px;opacity:.62}
.pr-list p.pr-t{font-size:16px;line-height:1.35;font-weight:600;opacity:1;margin-bottom:4px}
.pr-links{display:flex;flex-wrap:wrap;gap:8px;margin:10px 0 0!important;opacity:1!important}
.pr-links a{font-family:var(--font-heading);font-weight:800;font-size:11px;letter-spacing:.08em;text-transform:uppercase;padding:5px 10px;border:2px solid var(--color-divider);color:var(--color-text)!important;text-decoration:none}
.pr-article{padding-top:40px;padding-bottom:100px}
.pr-article .pr-cols{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:48px;align-items:start;border-top:2px solid var(--color-divider);padding-top:32px;margin-top:32px}
.pr-article .pr-cols p{font-size:16px;line-height:1.7;margin:0 0 20px}
.pr-article figure{margin:0}.pr-article figure img{display:block;width:100%;height:auto;border:2px solid var(--color-divider);background:var(--color-surface)}
.pr-entry{padding:44px 0;border-bottom:1px solid var(--color-divider)}
.pr-entry time{font-family:var(--font-heading);font-weight:800;font-size:15px;color:var(--color-accent)}
#prerender .pr-entry h2{font-size:clamp(24px,3.4vw,34px);margin:8px 0 18px}
.pr-entry p{font-size:17px;line-height:1.85;max-width:58ch;margin:0 0 16px}
.pr-entry img{max-width:100%;height:auto}
.pr-foot{border-top:2px solid var(--color-divider);font-size:13px;opacity:.6}
.pr-foot .pr-wrap{padding-top:28px;padding-bottom:56px}
`.replace(/\n/g, '');

// Runs before paint: theme, language redirect, and removal of the static copy
// once the interactive page has drawn itself.
const bootScript = (site, redirectToAlt) => `<script>
window.__SITE=${JSON.stringify(site)};
(function(){try{
var d=document.documentElement,t=localStorage.getItem('site-theme');if(t)d.setAttribute('data-theme',t);
${redirectToAlt ? `var s=localStorage.getItem('site-lang'),ja=s?s==='ja':(navigator.language||'').toLowerCase().indexOf('ja')===0;
if(ja&&!/bot|crawl|spider|slurp|preview/i.test(navigator.userAgent)){location.replace(${JSON.stringify(redirectToAlt)}+location.hash);return;}` : ''}
}catch(e){}
new MutationObserver(function(m,o){var r=document.getElementById('dc-root'),p=document.getElementById('prerender');
if(r&&p&&r.textContent.trim().length>200){p.remove();o.disconnect();
var h=location.hash.slice(1),e=h&&h.indexOf('/')<0&&document.getElementById(h);if(e)e.scrollIntoView();}}).observe(document.documentElement,{childList:true,subtree:true});
})();
</script>`;

function head({ lang, title, description, canonical, alternates, image, type = 'website', ld, site, redirectToAlt, stylesheet }) {
  const img = image ? abs(image) : null;
  return `<!DOCTYPE html>
<!-- GENERATED by build-seo.mjs — do not edit. Edit content.js / diary.js, then run ./publish.sh -->
<html lang="${lang}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<meta name="description" content="${esc(description)}">
<meta name="author" content="Takumi Kuhara">
<meta name="robots" content="index,follow,max-image-preview:large">
<link rel="canonical" href="${esc(canonical)}">
${(alternates || []).map(a => `<link rel="alternate" hreflang="${a.lang}" href="${esc(a.href)}">`).join('\n')}
<meta property="og:type" content="${type}">
<meta property="og:site_name" content="Takumi Kuhara">
<meta property="og:title" content="${esc(title)}">
<meta property="og:description" content="${esc(description)}">
<meta property="og:url" content="${esc(canonical)}">
<meta property="og:locale" content="${lang === 'ja' ? 'ja_JP' : 'en_US'}">
${img ? `<meta property="og:image" content="${esc(img)}">\n<meta name="twitter:image" content="${esc(img)}">` : ''}
<meta name="twitter:card" content="${img ? 'summary_large_image' : 'summary'}">
<meta name="twitter:title" content="${esc(title)}">
<meta name="twitter:description" content="${esc(description)}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="preconnect" href="https://unpkg.com" crossorigin>
<link rel="stylesheet" href="${esc(stylesheet)}">
<style>${STATIC_CSS}</style>
${jsonld({ '@context': 'https://schema.org', '@graph': ld })}
${bootScript(site, redirectToAlt)}
<script src="./support.js" defer></script>
</head>`;
}

/* ---- pull the interactive page apart so we can wrap it ------------------- */
function splitDc(file) {
  const src = readFileSync(at(file), 'utf8');
  const open = src.indexOf('<x-dc');
  const close = src.lastIndexOf('</x-dc>') + '</x-dc>'.length;
  const scriptStart = src.indexOf('<script type="text/x-dc"');
  const scriptEnd = src.indexOf('</script>', scriptStart) + '</script>'.length;
  if (open < 0 || close < 7 || scriptStart < 0) throw new Error(file + ': could not find <x-dc> block or its script');
  const sheet = (/<link rel="stylesheet" href="([^"]+)"/.exec(src) || [])[1];
  if (!sheet) throw new Error(file + ': stylesheet link not found');
  return { template: src.slice(open, close), script: src.slice(scriptStart, scriptEnd), sheet };
}

// links inside the interactive template point at the source files; in the
// generated pages they should point at the generated, indexable ones.
const relink = (html, lang) => html
  .replace(/href="Diary\.dc\.html"/g, 'href="diary.html"')
  .replace(/href="Research(?: |%20)Portfolio\.dc\.html"/g, `href="${homeFile(lang)}"`);

const page = (headHtml, dc, prerender, lang, narrow) => `${headHtml}
<body>
<div id="prerender"${narrow ? ' class="pr-narrow"' : ''}>
${prerender}
</div>
${relink(dc.template, lang)}
${dc.script}
</body>
</html>
`;

/* ---- static copies of the content ---------------------------------------- */
function bar(lang, ui, deep) {
  const h = deep ? homeFile(lang) : '';
  return `<header class="pr-bar"><div>
<a class="pr-brand" href="${homeFile(lang)}">${esc(tr(C.PROFILE.name, lang))}</a>
<nav>
<a href="${h}#projects">${esc(ui.nav_projects)}</a>
<a href="${h}#about">${esc(ui.nav_about)}</a>
<a href="${h}#research">${esc(ui.nav_research)}</a>
<a href="${h}#cv">${esc(ui.nav_cv)}</a>
<a href="${h}#contact">${esc(ui.nav_contact)}</a>
<a href="diary.html">${esc(ui.nav_diary)}</a>
<a href="${deep ? projFile(deep, other(lang)) : homeFile(other(lang))}" hreflang="${other(lang)}" lang="${other(lang)}">${lang === 'en' ? '日本語' : 'English'}</a>
</nav></div></header>`;
}
const foot = ui => `<footer class="pr-foot"><div class="pr-wrap">${esc(ui.footer)}</div></footer>`;

const entryList = (items, lang, ui, wide) => `<ul class="pr-list${wide ? ' pr-wide' : ''}">
${items.map(p => `<li><span class="pr-y">${esc(p.year)}</span><div>
<p class="pr-t" lang="${langOf(p.title, lang)}">${esc(tr(p.title, lang))}</p>
${p.authors ? `<p>${esc(tr(p.authors, lang))}</p>` : ''}
${p.venue ? `<p><i>${esc(tr(p.venue, lang))}</i></p>` : ''}
${p.tags && tr(p.tags, lang) ? `<p>${esc(tr(p.tags, lang))}</p>` : ''}
${linkRow(linksOf(p, ui))}
</div></li>`).join('\n')}
</ul>`;

function homeBody(lang) {
  const ui = C.UI[lang], P = C.PROFILE, t = v => tr(v, lang);
  const socials = C.SOCIALS.filter(s => s.url || s.value);
  return `${bar(lang, ui)}
<main>
<section class="pr-wrap pr-hero">
<div>
<p class="pr-kicker">${esc(t(P.role))}</p>
<h1>${esc(t(P.name))}</h1>
<p class="pr-lead">${esc(t(P.tagline))}</p>
</div>
${P.portrait ? `<img class="grayscale" src="${esc(P.portrait)}" alt="${esc(t(P.name))}" width="300" height="400">` : ''}
</section>
<section class="pr-sec" id="projects"><div class="pr-wrap">
<h2>${esc(ui.projects_heading)}</h2>
<ul class="pr-cards">
${C.PROJECTS.map(p => `<li>
${p.image ? `<a href="${projFile(p.id, lang)}"><img class="grayscale" src="${esc(p.image)}" alt="${esc(t(p.title))}" loading="lazy"></a>` : ''}
<p class="pr-k">${esc(t(p.kicker))} · ${esc(p.year)}</p>
<h3><a href="${projFile(p.id, lang)}">${esc(t(p.title))}</a></h3>
<p>${esc(t(p.blurb))}</p>
</li>`).join('\n')}
</ul>
</div></section>
<section class="pr-sec" id="about"><div class="pr-wrap">
<h2>${esc(ui.about_heading)}</h2>
<p class="pr-text">${esc(t(P.about))}</p>
<ul class="pr-tags">${P.interests.map(i => `<li>${esc(t(i))}</li>`).join('')}</ul>
</div></section>
<section class="pr-sec" id="research"><div class="pr-wrap">
<h2>${esc(ui.research_heading)}</h2>
<h3>${esc(ui.publications_heading)}</h3>
${entryList(C.PUBLICATIONS, lang, ui)}
<h3>${esc(ui.presentations_heading)} — ${esc(ui.intl_heading)}</h3>
${entryList(C.PRESENTATIONS_INTL, lang, ui)}
<h3>${esc(ui.presentations_heading)} — ${esc(ui.domestic_heading)}</h3>
${entryList(C.PRESENTATIONS_DOMESTIC, lang, ui)}
<h3>${esc(ui.education_heading)}</h3>
<ul class="pr-list pr-wide">
${C.EDUCATION.map(e => `<li><span class="pr-y">${esc(t(e.years))}</span><div><p class="pr-t">${esc(t(e.text))}</p></div></li>`).join('\n')}
</ul>
${P.researchmap ? `<p class="pr-text" style="margin-top:28px"><a href="${esc(P.researchmap)}" rel="noopener me">${esc(ui.full_profile)}</a></p>` : ''}
</div></section>
${t(P.cvFile) ? `<section class="pr-sec" id="cv"><div class="pr-wrap">
<h2>${esc(ui.cv_heading)}</h2>
<p class="pr-text">${esc(ui.cv_body)} <a href="${esc(t(P.cvFile))}">${esc(ui.cv_button)}</a></p>
</div></section>` : ''}
<section class="pr-sec"><div class="pr-wrap">
<h2>${esc(ui.recs_heading)}</h2>
<ul class="pr-cards">
${C.RECOMMENDATIONS.map(r => `<li><h4>${r.url ? `<a href="${esc(r.url)}" rel="noopener">${esc(t(r.title))}</a>` : esc(t(r.title))}</h4><p>${esc(t(r.desc))}</p></li>`).join('\n')}
</ul>
</div></section>
<section class="pr-sec"><div class="pr-wrap">
<h2>${esc(ui.diary_cta_title)}</h2>
<p class="pr-text">${esc(ui.diary_cta_body)} <a href="diary.html">${esc(ui.diary_cta_button)}</a></p>
</div></section>
<section class="pr-sec" id="contact"><div class="pr-wrap">
<h2>${esc(ui.contact_heading)}</h2>
<p class="pr-text">${esc(ui.contact_intro)}</p>
<p class="pr-links">${socials.map(s => `<a href="${esc(s.value ? 'mailto:' + s.value : s.url)}" rel="noopener me">${esc(t(s.label))}</a>`).join(' ')}</p>
</div></section>
</main>
${foot(ui)}`;
}

function projectBody(p, lang) {
  const ui = C.UI[lang], t = v => tr(v, lang);
  return `${bar(lang, ui, p.id)}
<main><article class="pr-wrap pr-article">
<p><a href="${homeFile(lang)}#projects">← ${esc(ui.project_back)}</a></p>
<p class="pr-kicker">${esc(t(p.kicker))} · ${esc(p.year)}</p>
<h1>${esc(t(p.title))}</h1>
<p class="pr-lead">${esc(t(p.blurb))}</p>
<div class="pr-cols">
<div>
${p.body.map(b => `<p>${esc(t(b))}</p>`).join('\n')}
${linkRow(linksOf(p.links || {}, ui))}
<p style="margin-top:32px;font-size:14px;opacity:.7">${esc(t(C.PROFILE.name))} — ${esc(t(C.PROFILE.role))}</p>
</div>
${p.image ? `<figure><img class="grayscale" src="${esc(p.image)}" alt="${esc(t(p.title))}"></figure>` : ''}
</div>
</article></main>
${foot(ui)}`;
}

const entriesSorted = D.ENTRIES.slice().sort((a, b) => (a.date < b.date ? 1 : -1));
const fig = i => `<figure><img src="${esc(i.src)}" alt="${esc(i.alt || i.caption || '')}" loading="lazy">${i.caption ? `<figcaption>${esc(i.caption)}</figcaption>` : ''}</figure>`;
function diaryBody() {
  return `<header class="pr-bar"><div><a class="pr-brand" href="./">Takumi Kuhara</a><nav><a href="./">Research portfolio</a><a href="ja.html" lang="ja" hreflang="ja">日本語</a></nav></div></header>
<main class="pr-wrap">
<section style="padding:64px 0 40px;border-bottom:2px solid var(--color-divider)">
<p class="pr-kicker">Notebook</p>
<h1>Diary</h1>
<p class="pr-lead">Gadgets, papers, and things I found interesting. Written quickly, in whichever language the thought arrived in.</p>
</section>
${entriesSorted.map(e => `<article class="pr-entry" lang="${esc(e.lang || 'en')}">
<time datetime="${esc(e.date)}">${esc(e.date)}</time>
<h2>${esc(e.title)}</h2>
${(e.body || []).map(b => (b && typeof b === 'object') ? (b.src ? fig(b) : '') : `<p>${esc(b)}</p>`).join('\n')}
${(e.images || []).filter(i => i && i.src).map(fig).join('\n')}
</article>`).join('\n')}
</main>
<footer class="pr-foot"><div class="pr-wrap"><a href="./">Research portfolio</a></div></footer>`;
}

/* ---- assemble ------------------------------------------------------------ */
const portfolio = splitDc(PORTFOLIO_SRC);
const diary = splitDc(DIARY_SRC);
const out = {};
const sitemap = [];
const contentStamp = new Date(Math.max(mtime('content.js'), mtime(PORTFOLIO_SRC)));
const contentDate = isoDate(contentStamp);                                   // sitemap: date only
// Google's structured-data checker rejects a bare date here — it wants a full
// ISO 8601 timestamp with a timezone.
const contentDateTime = contentStamp.toISOString().replace(/\.\d+Z$/, 'Z');

for (const lang of LANGS) {
  const alternates = [
    { lang: 'en', href: homeUrl('en') }, { lang: 'ja', href: homeUrl('ja') }, { lang: 'x-default', href: homeUrl('en') }
  ];
  out[lang === 'en' ? 'index.html' : 'ja.html'] = page(head({
    lang, title: tr(SEO.title, lang), description: tr(SEO.description, lang),
    canonical: homeUrl(lang), alternates, image: C.PROJECTS.find(p => p.image)?.image || C.PROFILE.portrait,
    type: 'profile', stylesheet: portfolio.sheet,
    ld: [websiteLd, personLd(lang),
      { '@type': 'ProfilePage', '@id': homeUrl(lang) + '#page', url: homeUrl(lang), name: tr(SEO.title, lang), inLanguage: lang, isPartOf: { '@id': SITE + '/#website' }, mainEntity: { '@id': PERSON_ID }, dateModified: contentDateTime },
      ...(lang === 'en' ? C.PUBLICATIONS.map(articleLd) : [])],
    site: { lang, alt: homeFile(other(lang)), home: homeFile(lang), projectUrl: projFile('{id}', lang) },
    redirectToAlt: lang === 'en' ? homeFile('ja') : null
  }), portfolio, homeBody(lang), lang);
  sitemap.push({ loc: homeUrl(lang), lastmod: contentDate, alternates, priority: '1.0' });

  for (const p of C.PROJECTS) {
    const url = l => SITE + '/' + projFile(p.id, l);
    const palt = [{ lang: 'en', href: url('en') }, { lang: 'ja', href: url('ja') }, { lang: 'x-default', href: url('en') }];
    const name = tr(C.PROFILE.name, lang);
    const title = `${tr(p.title, lang)} | ${name}`;
    const doi = [p.links?.doi, ...(p.links?.more || []).map(m => m.href)].filter(u => u && /doi\.org/.test(u));
    out[projFile(p.id, lang)] = page(head({
      lang, title, description: clip(tr(p.blurb, lang), lang === 'ja' ? 120 : 165),
      canonical: url(lang), alternates: palt, image: p.image || C.PROFILE.portrait, type: 'article', stylesheet: portfolio.sheet,
      ld: [websiteLd, personLd(lang),
        { '@type': 'WebPage', '@id': url(lang) + '#page', url: url(lang), name: title, inLanguage: lang, isPartOf: { '@id': SITE + '/#website' }, dateModified: contentDateTime,
          primaryImageOfPage: p.image ? abs(p.image) : undefined,
          mainEntity: { '@type': 'ResearchProject', name: tr(p.title, lang), description: tr(p.blurb, lang), member: { '@id': PERSON_ID }, sameAs: doi.length ? doi : undefined },
          breadcrumb: { '@type': 'BreadcrumbList', itemListElement: [
            { '@type': 'ListItem', position: 1, name, item: homeUrl(lang) },
            { '@type': 'ListItem', position: 2, name: tr(p.title, lang), item: url(lang) }] } }],
      site: { lang, view: p.id, alt: projFile(p.id, other(lang)), home: homeFile(lang), projectUrl: projFile('{id}', lang) },
      redirectToAlt: lang === 'en' ? projFile(p.id, 'ja') : null
    }), portfolio, projectBody(p, lang), lang);
    sitemap.push({ loc: url(lang), lastmod: contentDate, alternates: palt, priority: '0.8' });
  }
}

const diaryUrl = SITE + '/diary.html';
const diaryDate = entriesSorted[0]?.date || isoDate(mtime('diary.js'));
out['diary.html'] = page(head({
  lang: 'en', title: SEO.diaryTitle, description: SEO.diaryDescription, canonical: diaryUrl,
  image: C.PROFILE.portrait, stylesheet: diary.sheet,
  ld: [websiteLd, personLd('en'), {
    '@type': 'Blog', '@id': diaryUrl + '#blog', url: diaryUrl, name: SEO.diaryTitle, author: { '@id': PERSON_ID },
    blogPost: entriesSorted.map(e => ({ '@type': 'BlogPosting', headline: e.title, datePublished: e.date + 'T12:00:00Z', inLanguage: e.lang || 'en', author: { '@id': PERSON_ID }, url: diaryUrl, articleBody: (e.body || []).filter(b => typeof b === 'string').join('\n\n') }))
  }],
  site: { page: 'diary' }
}), diary, diaryBody(), 'en', true);
sitemap.push({ loc: diaryUrl, lastmod: diaryDate, priority: '0.6' });

out['sitemap.xml'] = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
${sitemap.map(u => `  <url>
    <loc>${esc(u.loc)}</loc>
    <lastmod>${u.lastmod}</lastmod>
${(u.alternates || []).map(a => `    <xhtml:link rel="alternate" hreflang="${a.lang}" href="${esc(a.href)}"/>`).join('\n')}
    <priority>${u.priority}</priority>
  </url>`).join('\n').replace(/\n\n/g, '\n')}
</urlset>
`;
out['robots.txt'] = `User-agent: *\nAllow: /\n\nSitemap: ${SITE}/sitemap.xml\n`;

// Everything rendered without throwing — only now touch the disk.
let changed = 0;
for (const [file, text] of Object.entries(out)) {
  const old = existsSync(at(file)) ? readFileSync(at(file), 'utf8') : null;
  if (old !== text) { writeFileSync(at(file), text); changed++; }
}
console.log(`build-seo: ${Object.keys(out).length} files checked, ${changed} written`);
